### ISSUE TITLE
输入batch_x和placeholder维度不一致

### ISSUE THREAD

**Issue by XgSuen** [ChenNed/CasCN#1]
陈教授您好，请问run_sparse_graph_signal 283行self.x placeholder定义的维度和 run_graph_sequence 126行输入的batch_x维度不一致，您可以帮忙解决一下吗？

**Comment by 1172300310** [comment]
> 陈教授您好，请问run_sparse_graph_signal 283行self.x placeholder定义的维度和 run_graph_sequence 126行输入的batch_x维度不一致，您可以帮忙解决一下吗？

请问怎么解决的？
